services:
  web:
    build:
      context: .
      args:
        SOURCE_REPO: ${SOURCE_REPO}
    image: ghcr.io/${DOCKER_REGISTRY}/openagri-userdashboard:${TAG}
    ports:
      - "${SERVICE_PORT}:${SERVICE_PORT}"
    environment:
      SERVICE_PORT: ${SERVICE_PORT}
