services:
  web:
    build:
      context: .
      args:
        SOURCE_REPO: ${SOURCE_REPO}
        VITE_PRIMARY_COLOR: ${VITE_PRIMARY_COLOR}
        VITE_SECONDARY_COLOR: ${VITE_SECONDARY_COLOR}
        VITE_BACKGROUND_DEFAULT: ${VITE_BACKGROUND_DEFAULT}
        VITE_BACKGROUND_PAPER: ${VITE_BACKGROUND_PAPER}
    image: ghcr.io/${DOCKER_REGISTRY}/openagri-userdashboard:${TAG}
    ports:
      - "${SERVICE_PORT}:${SERVICE_PORT}"
    environment:
      SERVICE_PORT: ${SERVICE_PORT}
